//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HspcuiBase.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HspcuiBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ソースコードは {0} です。 {0} としてコンパイルします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompileCharset {
            get {
                return ResourceManager.GetString("CompileCharset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を実行できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CouldNotRun {
            get {
                return ResourceManager.GetString("CouldNotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} ランタイムを実行できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CouldNotRunRuntime {
            get {
                return ResourceManager.GetString("CouldNotRunRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundA {
            get {
                return ResourceManager.GetString("NotFoundA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された {0} フォルダが見つかりませんでした。({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundSpecifyADirectory {
            get {
                return ResourceManager.GetString("NotFoundSpecifyADirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたソースファイルが .hsp ファイルではないため、AssemblyInfo.hsp は生成されませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotGenerateAssemblyInfo {
            get {
                return ResourceManager.GetString("NotGenerateAssemblyInfo", resourceCulture);
            }
        }
    }
}
